# Generated by Django 4.2.13 on 2024-06-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('avater', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('wallet', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
